openapi: 3.0.0
info:
  title: Paper Site API
  version: 1.0.0
  description: API for file uploading and user authentication

security:
  - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /api/auth/log-in:
    post:
      summary: Log in to the server
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: User logged in succesfully
    
  /api/auth/sign-up:
    post:
      summary: Sign up a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: User signed up successfully
  
  /api/auth/is-verify:
    get:
      summary: Verify user token
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Token is valid
    
  /api/dashboard:
    get:
      summary: Get user information
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User information retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  email:
                    type: string
        '401':
          description: Unauthorized
          
  /api/dashboard/user/delete{id}:
    delete:
      summary: Delete user
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: ID of the user to delete
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: User deleted successfully
        '401':
          description: Unauthorized
          
  /api/dashboard/upload:
    post:
      summary: Upload file
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: File uploaded successfully
        '400':
          description: Invalid request
          
  /api/dashboard/delete/{fileId}:
    delete:
      summary: Delete file
      security:
        - bearerAuth: []
      parameters:
        - name: fileId
          in: path
          description: ID of the file to delete
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: File deleted successfully
        '401':
          description: Unauthorized
        '404':
          description: File not found
  
  /api/papers:
    get:
      summary: Get all files
      responses:
        '200':
          description: List of files retrieved successfully
    
  /api/papers/{id}:
    get:
      summary: Get file by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: File retrieved successfully
  
  /api/papers/{course}:
    get:
      summary: Get file by ID
      parameters:
        - in: path
          name: course
          required: true
          schema:
            type: string
      responses:
        '200':
          description: File retrieved successfully
  